---
language: rust

rust:
  - stable
  - beta
  - nightly
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
- rustup component add rustfmt
- cargo +nightly install --force rustfmt-nightly

script:
  - cargo +nightly fmt --all -- --check
  - cargo build --verbose --all